[KIECLOUD-448] - Provide automated way to update product version on R…
jboss-container-images/jboss-kie-modules pull request #425
Opened 2021-01-14 15:57 UTC by spolti

…HPAM and RHDM repositories

Signed-off-by: spolti <fspolti@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [X] Pull Request title is properly formatted: `[KIECLOUD-XYZ] Subject`, `[RHDM-XYZ] Subject` or `[RHPAM-XYZ] Subject`
- [X] Pull Request contains link to the JIRA issue
- [X] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket
- [X] Attached commits represent units of work and are properly formatted
- [X] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [X] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2021-01-15 18:43 UTC, msmagnanijr submitted a review, later dismissed
lgtm

2021-01-17 13:48 UTC, Kaitou786 requested changes

2021-01-17 13:48 UTC, Kaitou786 commented on tools/update-version/update-version.py
> +#   python scripts/update-version.py -v 7.15.1
Can you please change update the script location with the correct path `tools/update-version/update-version.py` also calling it with `python3` and giving one more example with `--confirm` flag. Thanks.

2021-01-17 13:48 UTC, Kaitou786 commented
Apart from the above comment, script looks good to me :)

2021-01-18 12:00 UTC, Kaitou786 approved these changes

2021-01-18 13:31 UTC, merged