[RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image
jboss-container-images/jboss-kie-modules pull request #540
Opened 2022-03-14 10:21 UTC by desmax74

See: https://issues.redhat.com/browse/RHPAM-3528
Signed-off-by: desmax74 <mdessi@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[KIECLOUD-XYZ] Subject`, `[RHDM-XYZ] Subject` or `[RHPAM-XYZ] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2022-03-14 10:59 UTC, spolti submitted a review, later dismissed

2022-03-17 15:37 UTC, jakubschwan reviewed
Changes looks good to me.
@desmax74 can you please extend behave tests and cover there configuration of the max-pool-size as well? Right now there is only covered max session value. It would by good to have there tests covering default configuration, set only session count with applied default max pool size and also test for configured max session and max pool.

2022-03-17 17:54 UTC, spolti requested changes

2022-03-17 17:54 UTC, spolti commented on jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
> +    unset JBOSS_KIE_EXECUTOR_MDB_MAX_SESSIONS
this one was left behind :)

2022-03-17 17:55 UTC, desmax74 commented on jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
> +    unset JBOSS_KIE_EXECUTOR_MDB_MAX_SESSIONS
Right :)

2022-03-17 17:59 UTC, desmax74 commented on jboss-kie-kieserver/added/launch/jboss-kie-kieserver-jms.sh
> +    unset JBOSS_KIE_EXECUTOR_MDB_MAX_SESSIONS
fixed

2022-03-17 18:31 UTC, spolti commented on tests/features/common/kie-kieserver-common.feature
> +    And file /opt/eap/standalone/configuration/standalone-openshift.xml should not contain <strict-max-pool name="mdb-strict-max-pool" derive-size="from-cpu-count"
I think what Max did is correct, it should not contain the derive property if the max session is set

2022-03-17 18:40 UTC, merged